<?php

/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    '(not set)' => '',
    'Authorised Sellers:' => 'البائعون المُعتمَدون:',
    'iPower' => 'مجموعة',
    'Collection' => 'طاقة آيباور',
    'Experience the Ultimate in' => 'استمتع بتجرُبة شحن مثاليّة، سريعة،',
    'Fast, Safe, and Portable Charging' => 'آمنة، تصطحِبها معك لكلّ مكان',
    'Participate in the Lucky Draw' => 'جرّب حظّك في السَحب الآن',
    'Authorization' => 'إذن',
    'Save changes' => 'يُقدِّم',
    'Submit' => 'يُقدِّم',
    'Close' => 'يغلق',
    'Login Code' => 'رمز تسجيل الدخول',
    'Try My Luck' => 'جرب حظي',
    'Verification failed: Invalid login code' => 'فشل التحقق: رمز تسجيل الدخول غير صالح',
    'Hurry: you have won the' => 'أسرع: لقد فزت بالجائزة',
    'Claim your gift' => 'المطالبة هديتك',
    'Congratulations!' => 'تهانينا لك!',
    'You have won the' => 'لقد فزت',
    'from lucky draw, claim your gift now!' => 'من السحب المحظوظ، احصل على هديتك الآن!',
    'Verification failed: Invalid item code' => 'فشل التحقق: رمز العنصر غير صالح',
    'First Name' => 'الاسم الصريح',
    'Last Name' => 'اسم العائلة ',
    'Email' => 'إيميل التواصُل',
    'Phone' => ' رقم الهاتف المحمول',
    'Address Line 1' => 'العنوان سطر 1',
    'Address Line 2' => 'سطر العنوان 2',
    'Landmark' => 'معلم',
    'City' => 'مدينة',
    'Item Code' => 'رمز العنصر',
    'Purchase Date' => 'تاريخ الشراء',
    'Purchase Place' => 'متجر البَيع',
    'Invoice File' => 'ملف الفاتورة',
    'Verification successful, Redirecting...' => 'تم التحقق بنجاح، جارٍ إعادة التوجيه...',
    'Verification failed: Invalid login code' => 'فشل التحقق: رمز تسجيل الدخول غير صالح',
    'Sending....' => 'إرسال....',
    'Gift request successfully send' => 'تم إرسال طلب الهدية بنجاح',
    'Activation Code' => 'رمز التنشيط ',
    'Please enter the 4-digit login code found inside your box to continue' => 'الرجاء إدخال الرمز المكوّن من أربع خانات الخاصّ بتسجيل الدخول، الموجود داخل العُلبة، من أجل إكمال عمليّة تقديم الطلَب. ',
    'Participate in the Lucky Draw' => 'شارِك في عمليّة السَحب وجرّب حظك! ',
    'Spin the Wheel' => 'قُم بتدوير عجَلة المُسابقة ',
    'Congratulations! You have won a' => 'نُهنِّئك! أنتَ الرابح ولقد حصلت على',
    'Claim your gift' => 'احصل الآن على هديّتك المُميزة',
    'Upload Invoice/Proof of Purchase' => 'تحميل الفاتورة الخاصّة بعمليّة الشراء/ إثبات عمليّة الشراء',
    'Gift Code' => ' الرقم الخاصّ بالهديّة',
    'Thank You for submitting, you will receive an email from us shortly!' => 'شُكرًا لك على إتمام عمليّة الإرسال، سوف تتلقّى بريدًا إلكترونيًا للردّ على طلبك قريبًا!',
    'Exclusively Available in:' => 'متوفر حصريا في:',
    'Terms & Conditions' => 'الشروط والأحكام'
];

